name: Docker CI Go Server GRPC
env:
  DOCKER-TAG: $(date +%s)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set the value tag
      id: step_one
      run: |
        echo "DOCKER-TAG=$(date +%s)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/go-server-greet:${{env.DOCKER-TAG}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/go-server-greet:${{env.DOCKER-TAG}}
